version: "3"

services: 

    nginx:
        build: ./nginx
        ports:
          - "80:80"
        links:
          - "php"
        volumes:
          - ./opt:/opt
          - ./opt/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./opt/nginx/vhost:/etc/nginx/conf.d

    php:
        build: ./php
        ports:
          - "9000:9000"
        links:
          - "mysql"
        volumes:
          - ./opt/code:/opt/code
          - ./opt/php/php-fpm.d:/usr/local/etc/php-fpm.d
          - ./opt/php/conf.d:/usr/local/etc/php/conf.d
          - ./opt/php/supervisor:/etc/supervisor

    mysql:
        image: mysql:5.7
        ports:
          - "3306:3306"
        volumes:
          - mysql-data:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: "123456"
    redis:
        image: redis:5.0.4
        ports:
          - "6379:6379"
        volumes:
          - ./opt/redis/redis.conf:/usr/local/etc/redis/redis.conf
          - ./opt/redis/log:/var/log/redis
          - ./opt/redis/data:/data
        command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  mysql-data: