version: "3"

services: 

    nginx:
        image: nas_nginx
        ports:
          - "80:80"
        depends_on:
          - "php"
        volumes:
          - /nas/opt:/var/www/html
          - /nas/opt/nginx/nginx.conf:/etc/nginx/nginx.conf
          - /nas/opt/nginx/vhost:/etc/nginx/conf.d
        deploy:
          mode: replicated
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 10

    php:
        image: nas_php
        ports:
          - "9000:9000"
        volumes:
          - /nas/opt/code:/var/www/html/code
          - /nas/opt/php-fpm:/usr/local/etc/php-fpm.d
        deploy:
          mode: replicated
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 10
